### ISSUE TITLE
Where can I find the Downloaded Courses?

### ISSUE THREAD

**Issue by elharony** [FrontendMasters/android-issues#5]
## Briefly:
Where exactly can I find the downloaded courses in the Internal Storage?

## Explanation:
- I've checked my Internal Space, it was 1 GB free. The External was 13 GB free.
- Then tried to download a few lessons
- The Internal Space becomes 0
> That's why I assumed in #4 that downloaded files are downloaded directly to the Internal Storage.
- After that; I've been searching through my Internal Space's Directories/Files and I didn't find the downloaded courses!

## How this can be fixed?
- A new directory called `Frontend Masters` should be created in the Internal/External Storage (Check #4)
- This directory will contain a sub-directory for each course
- Each sub-directory would have all downloaded videos

This would make it MUCH easier for the users to find the downloaded files,  Copy them to their External Storage Manually, or even watch them from another device!

**Comment by pragmaticpi** [comment]
Also, I checked my android folder, there was no mention of your android package files. A few hours back, I downloaded one course. It indeed using internal storage. But how come your downloaded files does not have a name.

**Comment by pradeepb6** [comment]
+1

**Comment by oluwatbi** [comment]
Same issues here

**Comment by lecollage** [comment]
I have the same.
I tried to look for this directory but didn't find it. I thought that I would find it and create a link to SD card. I don't understand how it's possible. Does this application create a kind of hidden directory?

**Comment by antoniosamay** [comment]
Any updates on this issue?

**Comment by dachev** [comment]
Hello from the team,

After debating the issue internally we agreed that it's important to allow storing downloads on external media. This will give Android users the freedom to save as much offline content as they desire, bypassing the capacity limitations imposed by their device.

However, we would have to protect the content from playback on unauthorized devices due to the following reasons:
  - it would be unfair to our instructors whose compensation is determined by playback stats
  - we would lose the ability to automatically fix errors and make updates which is essential in the fast-changing world of tech thus putting a strain on our support infrastructure and content quality

At this moment, we plan to allow storing videos offline on external media, but we can't commit to a precise timeline. We'll keep track of the effort in #4
